name: Collect Bookmarks, and backup

on:
  push:
    branches: [ master ]
#   schedule:
#     # * is a special character in YAML so you have to quote this string
#     - cron:  '0 * * * *'    

concurrency: staging_environment

jobs:
  collect_bookmarks:
    runs-on: ubuntu-latest
    steps:
      - name: Create Dir structure
        run: |
          mkdir personal-vault  
      - name: Checkout Package
        uses: actions/checkout@v2
        with:
          repository: ashutoshsaboo/personal-vault
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: ./personal-vault/
      - name: Test Dir structure
        run: |
          ls
          ls personal-vault/
          cd personal-vault/
          ls scripts/
          git status
      - name: Git-Crypt Unlock
        uses: zemuldo/git-crypt-unlock@v2.0
        env: 
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_KEY_GRIP: ${{ secrets.GPG_KEY_GRIP }}
          GPG_KEY_PASS: ${{ secrets.GPG_KEY_PASS }}
          

        
